### ISSUE TITLE
Malloc failure in lab0

### ISSUE THREAD

**Issue by seineo** [JonnyKong/CMU-15-213-Intro-to-Computer-Systems#2]
I met an error in this lab. The error messages are as follows.

Test of malloc failure on insert_head
ERROR: Freed queue, but 4 blocks are still allocated
---	trace-11-malloc	0/7
+++ TESTING trace trace-12-malloc:
Test of malloc failure on insert_tail
ERROR: Freed queue, but 3 blocks are still allocated
---	trace-12-malloc	0/7

At first, I used my own code. It failed. Then, I try to imitate your code(Sorry,  I just want to figure out why),but it still failed. I post essential part of code here:

```c
void q_free(queue_t *q)
{
    /* How about freeing the list elements and the strings? */
    if(q == NULL) {
    	return;
    }
    list_ele_t* p = q->head,*cur;
    while(p != NULL) {
        cur = p;
        p = p->next;
        free(cur->value);
        free(cur);
    }
    /* Free queue structure */
    free(q);
    q = NULL;
}

bool q_insert_head(queue_t *q, char *s)
{
    if(q == NULL) {
        return false;
    }
    /*...*/
}

bool q_insert_tail(queue_t *q, char *s)
{
    if(q == NULL) {
    	return false;
    }
    /*...*/
}
```

`q` has been set `NULL`, why are blocks still allocated?
 
Your kind help would be great appreciated.
Thanks in advance.

**Comment by JonnyKong** [comment]
I'm unable to reproduce this error. Can you elaborate on how this error can be reproduced?

**Comment by seineo** [comment]
I'm afraid that you've got to clone my repository `Workshop` since the files are in its sub-directory. Here's the SSH : `git@github.com:seineo/Workshop.git`. 

In the `cprogramminglab` directory,  open the terminal : 
> linux> make
   linux> make test

Then you can see this error.

**Comment by JonnyKong** [comment]
Your lab has different spec than mine. In my lab each list node contains an int:
`bool q_insert_head(queue_t *q, int v);`
But your list node contains a string:
`bool q_insert_head(queue_t *q, char *s);`

**Comment by seineo** [comment]
I know that, but I don't think it make a difference...
It seems that the problem can't be resolved, but  thank you, again.

**Comment by JonnyKong** [comment]
> I know that, but I don't think it make a difference...
> It seems that the problem can't be resolved, but thank you, again.

I think it does make a difference, since strings requires `malloc()` and `free()`? You can take a look a the pull request I made, which eliminates the errors above.

**Comment by seineo** [comment]
> > I know that, but I don't think it make a difference...
> > It seems that the problem can't be resolved, but thank you, again.
> 
> I think it does make a difference, since strings requires `malloc()` and `free()`? You can take a look a the pull request I made, which eliminates the errors above.

As to strings, I did `malloc()` and `free()`, which is also part of reasons that I'm confused about the errors. 

Besides, in the request you've made, you deleted the operations after `free(q)` (even delete `q = NULL`). Could you please explain why it can eliminate the errors？I tried this before, and it didn't work...

**Comment by JonnyKong** [comment]
> > > I know that, but I don't think it make a difference...
> > > It seems that the problem can't be resolved, but thank you, again.
> > 
> > 
> > I think it does make a difference, since strings requires `malloc()` and `free()`? You can take a look a the pull request I made, which eliminates the errors above.
> 
> As to strings, I did `malloc()` and `free()`, which is also part of reasons that I'm confused about the errors.
> 
> Besides, in the request you've made, you deleted the operations after `free(q)` (even delete `q = NULL`, on principle, we should set `NULL` after `free()`). Could you please explain why it can eliminate the errors？I tried this before, and it didn't work...

1) I think the errors were eliminated because I added two free() calls in queue.c.
2) It's not necessary to set q to NULL, because q is a pointer that's passed by value, so it doesn't make a difference after the function returns. You should set the pointer to NULL in the parent function.

**Comment by seineo** [comment]
I forgot the pointer is passed by value then. Thanks for your patient explanation.
However, what I see in queue.c is that you make some deletion(4 lines) instead of adding free() calls :
[Your commit](https://github.com/JonnyKong/CMU-15-213-Intro-to-Computer-Systems/commit/eaecb4cea16788819cf5ccb605d9bb41a482ef8d)

Is there anything wrong?

**Comment by JonnyKong** [comment]
> I forgot the pointer is passed by value then. Thanks for your patient explanation.
> However, what I see in queue.c is that you make some deletion(4 lines) instead of adding free() calls :
> [Your commit](https://github.com/JonnyKong/CMU-15-213-Intro-to-Computer-Systems/commit/eaecb4cea16788819cf5ccb605d9bb41a482ef8d)
> 
> Is there anything wrong?

These 4 lines won't necessarily cause runtime bugs, but causes undefined behavior (since I already called `free(p)`, further operations on `p` is undefined behavior).

**Comment by seineo** [comment]
I know that.. but thank you anyway.
